#!/usr/bin/env python3
"""
KMC扩散参数自动计算工具
用于生成kmc_params.txt文件
"""

import numpy as np

# 原子半径数据库（Å）
ATOMIC_RADII = {
    'Cu': 1.28, 'Ag': 1.44, 'Au': 1.44,
    'Zr': 1.60, 'Ti': 1.47, 'Hf': 1.59,
    'Cr': 1.27, 'Mo': 1.39, 'W': 1.39,
    'Ni': 1.24, 'Co': 1.25, 'Fe': 1.26,
    'Al': 1.43, 'Mg': 1.60,
    'S': 1.04, 'Se': 1.17, 'Te': 1.37,
}

# 迁移能估算数据库（eV）- 从文献收集
MIGRATION_ENERGIES = {
    # 在Cu中的迁移能
    ('Cu', 'Cu'): 0.7,   # Cu自扩散
    ('Zr', 'Cu'): 1.8,   # Zr在Cu中（估算，尺寸失配大）
    ('Cr', 'Cu'): 0.8,   # Cr在Cu中
    ('Ti', 'Cu'): 1.6,   # Ti在Cu中（估算）
    ('Ni', 'Cu'): 0.75,  # Ni在Cu中
    ('Al', 'Cu'): 1.0,   # Al在Cu中（估算）
    ('S', 'Cu'): 0.8,    # S在Cu中（估算）
}

def estimate_migration_energy(solute, solvent):
    """
    估算迁移能（如果没有文献数据）
    
    基于尺寸失配的简单模型：
    Em ≈ Em_solvent * (1 + 0.5 * (Δr/r)²)
    """
    if (solute, solvent) in MIGRATION_ENERGIES:
        return MIGRATION_ENERGIES[(solute, solvent)]
    
    # 从尺寸失配估算
    r_solvent = ATOMIC_RADII.get(solvent, 1.3)
    r_solute = ATOMIC_RADII.get(solute, 1.3)
    
    delta_r = (r_solute - r_solvent) / r_solvent
    
    Em_solvent = MIGRATION_ENERGIES.get((solvent, solvent), 0.7)
    
    # 修正因子
    Em = Em_solvent * (1 + 0.5 * delta_r**2)
    
    return max(0.5, min(Em, 3.0))  # 限制在合理范围


def compute_vacancy_formation_energy_gpumd(solute, solvent, nep_file):
    """
    使用GPUMD计算空位形成能
    
    这需要运行实际的GPUMD模拟
    这里只是框架
    """
    print(f"计算 {solute} 在 {solvent} 中的空位形成能...")
    print("需要运行GPUMD模拟")
    print("返回None，需要手动提供")
    return None


def generate_kmc_params(solutes, solvent='Cu', nep_file=None, output_file='kmc_params.txt'):
    """
    生成KMC参数文件
    
    参数：
        solutes: 溶质列表，例如 ['Zr', 'Cr']
        solvent: 溶剂，默认Cu
        nep_file: NEP势函数文件（用于计算Ef）
        output_file: 输出文件名
    """
    
    print("=" * 80)
    print("生成KMC扩散参数文件")
    print("=" * 80)
    print()
    
    params = []
    
    for solute in solutes:
        print(f"【{solute}】")
        
        # 空位形成能（需要计算或提供）
        if nep_file:
            Ef = compute_vacancy_formation_energy_gpumd(solute, solvent, nep_file)
        else:
            Ef = None
        
        if Ef is None:
            # 使用默认值
            Ef_default = {
                'Zr': 1.35,
                'Cr': 1.55,
                'S': 1.47,
            }
            Ef = Ef_default.get(solute, 1.0)
            print(f"  Ef = {Ef:.3f} eV（使用默认值）")
        else:
            print(f"  Ef = {Ef:.3f} eV（计算值）")
        
        # 迁移能（从数据库或估算）
        Em = estimate_migration_energy(solute, solvent)
        print(f"  Em = {Em:.3f} eV")
        
        # 原子质量
        masses = {
            'Zr': 91.22, 'Cr': 52.00, 'S': 32.07,
            'Cu': 63.55, 'Ti': 47.87, 'Ni': 58.69,
        }
        mass = masses.get(solute, 50.0)
        
        params.append({
            'species': solute,
            'Ef': Ef,
            'Em': Em,
            'mass': mass
        })
        
        print()
    
    # 写入文件
    with open(output_file, 'w') as f:
        f.write("# KMC Diffusion Parameters\n")
        f.write(f"# Solvent: {solvent}\n")
        f.write("# Generated by kmc_params_generator.py\n")
        f.write("#\n")
        f.write("# species  Ef(eV)  Em(eV)  mass(amu)  source\n")
        
        for p in params:
            source = "estimated" if (p['species'], solvent) not in MIGRATION_ENERGIES else "literature"
            f.write(f"{p['species']:<10} {p['Ef']:.3f}   {p['Em']:.3f}   {p['mass']:.2f}     {source}\n")
    
    print(f"✓ 参数文件已保存到: {output_file}")
    print()
    
    return params


# 使用示例
if __name__ == '__main__':
    print("KMC参数生成工具")
    print("=" * 80)
    print()
    
    print("示例1：生成Zr和Cr在Cu中的参数")
    generate_kmc_params(['Zr', 'Cr'], 'Cu')
    
    print("\n示例2：生成其他体系的参数")
    generate_kmc_params(['Ti', 'Ni'], 'Cu', output_file='kmc_params_Ti_Ni.txt')
    
    print("\n使用方法：")
    print("1. 运行此脚本生成参数文件")
    print("2. 手动检查和调整参数（可选）")
    print("3. 在run.in中使用：kmc_diffusion 800 1e-6 kmc_params.txt")
